### ISSUE TITLE
Long form doesn't scroll on iPhone

### ISSUE THREAD

**Issue by BartHuis** [codrops/ModalWindowEffects#12]
if you make a modal with a long form in it, and you open it on iphone, you can only scroll the inside of the modal by touching the whitespace. when you touch the form and scroll it up, is scrolls the page on the background, like your touching trough the input field. this does not happen with bootstrap modals.

**Comment by crnacura** [comment]
Do you have a demo that I can take a look at?

**Comment by BartHuis** [comment]
no, sorry, i dont work at that company anymore, and the part of that site what had the popup, is temporaraly removed. you'll have to make some your own.
